### ISSUE TITLE
compared to email-spec?

### ISSUE THREAD

**Issue by daniely** [contently/action_mailer_matchers#2]
Hi, thanks for the very cool matchers. I'm all for having options...but I was curious what the differences are to https://github.com/email-spec/email-spec

**Comment by aaackerman** [comment]
Hi @daniely, great question! When I was first building ActionMailerMatchers with the folks here at Contently, I took a look at `email-spec` and felt like the gem was a little heavy for our specific needs. 

If you look in the [`user_mailer_spec.rb` example](https://github.com/email-spec/email-spec/blob/master/examples/rails4_root/spec/models/user_mailer_spec.rb) in the repo, it looks like the matchers are being used to unit test the mailer objects specifically. That's great, but the purpose of the `have_received_email` matcher is to be used in controllers and other services to make sure that emails are being sent when actions are performed. You can see more clearly how `action_mailer_matchers` could be used by rewriting email-spec's [welcome controller test example](https://github.com/email-spec/email-spec/blob/master/examples/rails4_root/spec/controllers/welcome_controller_spec.rb). 

```
describe "POST /signup (#signup)" do
  it "should deliver the signup email" do
      expect {
        post :signup, "Email" => "email@example.com", "Name" => "Jimmy Bean"
      }.to change(ActionMailer::Base.deliveries, :size).by(1)

      last_delivery = ActionMailer::Base.deliveries.last
      expect(last_delivery.to).to include "email@example.com"
      #message is now multipart, make sure both parts include Jimmy Bean
      expect(last_delivery.parts[0].body.to_s).to include "Jimmy Bean"
      expect(last_delivery.parts[1].body.to_s).to include "Jimmy Bean"
  end
end
```

With ActionMailerMatchers

```
describe "POST /signup (#signup)" do
  it "should deliver the signup email" do
    post :signup, "Email" => "email@example.com", "Name" => "Jimmy Bean"
    expect("email@example.com").to have_received_email(body: "Jimmy Bean")
  end
end
```

If you think an idea from `email-spec` would be a good addition to this gem, we're happy to hear suggestions or accept pull requests!
