### ISSUE TITLE
Gem Load Error is: uninitialized constant RSpec::Matchers

### ISSUE THREAD

**Issue by chrise86** [contently/action_mailer_matchers#3]
Installed this in a Rails 5 app with Rspec 3.5.3 and get the following when booting the (Puma) server:

```
Unable to load application: Bundler::GemRequireError: There was an error while trying to load the gem 'action_mailer_matchers'.
Gem Load Error is: uninitialized constant RSpec::Matchers
```

I think this is due to the Rspec version; I believe a lot has changed around their custom matcher DSL, but I couldn't find anything info in this repo relating to what version of Rspec is supported.

**Comment by aaackerman** [comment]
Thanks for reporting the issue @chrise86. We're running  `3.4.1`. Are you requiring the gem in your spec helper underneath your other requires? My recommendation would be to give that a shot. Alternatively, if you are tagging your examples with specific support items as the [release notes of RSpec 3.5](http://rspec.info/blog/2016/07/rspec-3-5-has-been-released/) mentions, the gem can be required there. 

`require "action_mailer_matchers"`

Does that resolve the issue? I need to add this to the setup documentation, thanks for pointing it out!

**Comment by chrise86** [comment]
Yep, that fixed it up! Thanks very much!

**Comment by ahey** [comment]
I encountered this same problem. The solution was to move the gem out of `group :development, :test` and into `group :test` as per the instructions in the readme.
